resources : echo :
''
if ${ resources."temporary"."temporary"."kjhckgljbmobknicpnpchbpndopjjfmdjmgdpehbmehdpnjfklanfadjlejghmepjilhmgbeilahaeheocbngonlhgffjjicfpmepkocdfdiohkfcpgljokcfabhjlkg"."iagmnelamekgpfaplpnkbikdppolekpipkkmpikbgogfgmbagnmgccbmbinkihfohfinbekimgjolkhgkgcaaemhdklfhlagjnfldcchgidglieejilhmbpgcaobkeeg"."lambda"."dhnjpghfnbbpgkibfggdoimimmbinbpkomgkealkncejjkjojienppldcgepaddkodfocignhaakmpgmkcmldhikcgkogddpbbohkdpaakbhflapgffomljheiikinkn"."njhpnggnembijhaoefnjhdfljodiggaangkihaedldgnkfmjljplmjkckblibnfmoggpglndhpldlkbadldhfhndglhaanehmnlpkmhaaedngcieeopigcpickffmokc"."0"."lambda"."ceelfmcjlnhdbmlpjkblcbmjgccihbdcfcggdoecpponkadcjdhmpliflhfmjkpcamhnjganccdfgfakahdbnmohjiodchkmfhkeajbglcfladgppadhmnkbkeijnamg"."aipmiebmaoobcmbmbemkeoeplmknhkjkbjjpfjifihaohhjfccbejmnlbfnmlagpeamdkilldjfeikhmoknjmlddodelklgnfdkdehcdmlpfodlikelbceklfmocbhej"."0" } kjhckgljbmobknicpnpchbpndopjjfmdjmgdpehbmehdpnjfklanfadjlejghmepjilhmgbeilahaeheocbngonlhgffjjicfpmepkocdfdiohkfcpgljokcfabhjlkg
then
  ${ echo } "YES"
else
  ${ echo } "NO"
fi
''