TARGET=${e55dd2c8db9b224d0d6207c430354f481ece26fbf458400726e7624bcc79fcb72de81bccc55a066ebfa569317862dec4b13ea6bb4b1e8b0300f1dc867e51503d} &&
  NAME=${bdc6a3ee36ba1101872a7772344634fb07cf5dee5e77970db3dee38e697c0c1379d433ea03d0b61975f8d980d3dcc3c6516ff67db042cacf10cb3c27be1faf9b} &&
  if [ -t 0 ] || [[ "$( ${READLINK} /proc/self/fd/0 )" == pipe:* ]]
  then
    HAS_STANDARD_INPUT=true
      STANDARD_INPUT=$( ${TEE} )
  else
    HAS_STANDARD_INPUT=false &&
      STANDARD_INPUT=
  fi &&
  ${ECHO} STANDARD_OUTPUT=${STANDARD_OUTPUT} &&
  ${ECHO} STANDARD_ERROR=${STANDARD_ERROR} >&2 &&
  ${ECHO} INIT_NAME=${NAME} > ${TARGET} &&
  ${ECHO} INIT_HAS_STANDARD_INPUT=${HAS_STANDARD_INPUT} >> ${TARGET} &&
  ${ECHO} INIT_STANDARD_INPUT=${STANDARD_INPUT} >> ${TARGET} &&
  ${ECHO} INIT_ARGUMENTS=${@} >> ${TARGET} &&
  ${ECHO} INIT_TYPEOF=${TYPEOF} >> ${TARGET} &&
  ${ECHO} INIT_STANDARD_OUTPUT=${STANDARD_OUTPUT} >> ${TARGET} &&
  ${ECHO} INIT_STANDARD_ERROR=${STANDARD_ERROR} >> ${TARGET} &&
  ${ECHO} INIT_STATUS=${STATUS} >> ${TARGET} &&
  ${ECHO} INIT_TOKEN_ARGUMENTS=${TOKEN_ARGUMENTS} >> ${TARGET} &&
  ${ECHO} INIT_TOKEN_STANDARD_INPUT=${TOKEN_STANDARD_INPUT} >> ${TARGET} &&
  ${ECHO} INIT_TOKEN_11=$( ${CAT} $( ${TOKEN_1} ) ) >> ${TARGET} &&
  ${ECHO} INIT_TOKEN_12=$( ${CAT} $( ${TOKEN_1} ${TOKEN_ARGUMENTS} ) ) >> ${TARGET} &&
  ${ECHO} INIT_TOKEN_13=$( ${CAT} $( ${ECHO} ${TOKEN_STANDARD_INPUT} | ${TOKEN_1} ) ) >> ${TARGET} &&
  ${ECHO} INIT_TOKEN_14=$( ${CAT} $( ${ECHO} ${TOKEN_STANDARD_INPUT} | ${TOKEN_1} ${TOKEN_ARGUMENTS} ) ) >> ${TARGET} &&
  ${ECHO} IN INIT STATUS=${STATUS} >> /build/debug &&
  ${ECHO} IN INIT TARGET=${TARGET} >> /build/debug &&
  exit ${STATUS}