echo > /build/post &&
IFS="/" read -ra TEMPORARY_PATH_ARRAY <<< "${TEMPORARY_PATH}" &&
  INIT_ARGUMENT_STATUS=${TEMPORARY_PATH_ARRAY[0]} &&
  INIT_STANDARD_INPUT_STATUS=${TEMPORARY_PATH_ARRAY[1]} &&
  INIT_EXIT_STATUS=${TEMPORARY_PATH_ARRAY[2]} &&
  RELEASE_EXIT_STATUS=${TEMPORARY_PATH_ARRAY[3]} &&
  ${MKDIR} --parents /build/observed/temporary/${INIT_ARGUMENT_STATUS}/${INIT_STANDARD_INPUT_STATUS}/${INIT_EXIT_STATUS} &&
  ${CAT} ${TARGET} >> /build/observed/temporary/${INIT_ARGUMENT_STATUS}/${INIT_STANDARD_INPUT_STATUS}/${INIT_EXIT_STATUS}/${RELEASE_EXIT_STATUS}