TARGET=${e55dd2c8db9b224d0d6207c430354f481ece26fbf458400726e7624bcc79fcb72de81bccc55a066ebfa569317862dec4b13ea6bb4b1e8b0300f1dc867e51503d} &&
  TEMPORARY_PATH=${bdc6a3ee36ba1101872a7772344634fb07cf5dee5e77970db3dee38e697c0c1379d433ea03d0b61975f8d980d3dcc3c6516ff67db042cacf10cb3c27be1faf9b} &&
  IFS="/" read -ra TEMPORARY_PATH_ARRAY <<< "${TEMPORARY_PATH}" &&
  A_INIT_ARGUMENT=${TEMPORARY_PATH_ARRAY[0]} &&
  A_INIT_STANDARD_INPUT=${TEMPORARY_PATH_ARRAY[1]} &&
  A_INIT_STANDARD_OUTPUT=${TEMPORARY_PATH_ARRAY[2]} &&
  A_INIT_STANDARD_ERROR=${TEMPORARY_PATH_ARRAY[3]} &&
  A_RELEASE_STANDARD_OUTPUT=${TEMPORARY_PATH_ARRAY[4]} &&
  A_RELEASE_STANDARD_ERROR=${TEMPORARY_PATH_ARRAY[5]} &&
  A_INIT_EXIT=${TEMPORARY_PATH_ARRAY[6]} &&
  A_RELEASE_EXIT=${TEMPORARY_PATH_ARRAY[7]} &&
  ${ECHO} RELEASE_STANDARD_OUTPUT=${A_RELEASE_STANDARD_OUTPUT} &&
  ${ECHO} RELEASE_STANDARD_ERROR=${A_RELEASE_STANDARD_ERROR} >&2 &&
  if [ -t 0 ] || [[ "$( ${READLINK} /proc/self/fd/0 )" == pipe:* ]]
  then
    RELEASE_HAS_STANDARD_INPUT=y
      RELEASE_STANDARD_INPUT=$( ${TEE} )
  else
    RELEASE_HAS_STANDARD_INPUT=n &&
      RELEASE_STANDARD_INPUT=
  fi &&
  ${ECHO} R_HAS_STANDARD_INPUT=${RELEASE_HAS_STANDARD_INPUT} > ${TARGET} &&
  ${ECHO} R_STANDARD_INPUT=${RELEASE_STANDARD_INPUT} >> ${TARGET} &&
  ${ECHO} R_A_INIT_ARGUMENT=${A_INIT_ARGUMENT} >> ${TARGET} &&
  ${ECHO} R_A_INIT_STANDARD_INPUT=${A_INIT_STANDARD_INPUT} >> ${TARGET} &&
  ${ECHO} R_A_INIT_STANDARD_OUTPUT=${A_INIT_STANDARD_OUTPUT} >> ${TARGET} &&
  ${ECHO} R_A_INIT_STANDARD_ERROR=${A_INIT_STANDARD_ERROR} >> ${TARGET} &&
  ${ECHO} R_A_INIT_EXIT=${A_INIT_EXIT} >> ${TARGET} &&
  ${ECHO} R_A_RELEASE_EXIT=${A_RELEASE_EXIT} >> ${TARGET} &&
  ${ECHO} R_VARIABLE=${VARIABLE} >> ${TARGET} &&
  exit ${A_RELEASE_EXIT}