#! /nix/store/9nw8b61s8lfdn8fkabxhbz0s775gjhbr-bash-5.2p37/bin/bash -e
export ORIGINATOR_PID='${ORIGINATOR_PID}'
export RESOURCE_NAME=$( ${BASENAME} $( ${DIRNAME} ${0} ) )
export RESOURCES=$( ${DIRNAME} $( ${DIRNAME} ${0} ) )
export STATUS='19'
exec "/nix/store/m128i4hz1mqzf47g7rq6nfnnz74chfa4-teardown/bin/teardown"  "$@" 
