name: Close Stale Pull Requests
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual execution

permissions:
  pull-requests: write    # Needed to close PRs and add comments

jobs:
  close_old_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches and history for the repo

      - name: Close PRs inactive for over 14 days
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Use your personal access token here
        run: |
          #!/bin/bash
          set -e

          # Get date from 14 days ago (in ISO 8601 format)
          fourteen_days_ago=$(date -u -d '14 days ago' +%Y-%m-%dT%H:%M:%SZ)

          echo "Date 14 days ago: $fourteen_days_ago"

          # Fetch open PRs and print out their details
          prs=$(gh pr list --state open --json number,updatedAt,createdAt --jq \
            '.[] | {number, updatedAt, createdAt}')

          echo "Found the following open PRs:"
          echo "$prs"

          # Loop over each PR to check if it is stale
          for pr in $(echo "$prs" | jq -r '. | {number} | @base64'); do
              # Decode each PR object from base64
              pr_json=$(echo "$pr" | base64 --decode)
              pr_number=$(echo "$pr_json" | jq -r '.number')
              pr_updated_at=$(echo "$pr_json" | jq -r '.updatedAt')
              pr_created_at=$(echo "$pr_json" | jq -r '.createdAt')

              echo "PR #$pr_number - Updated: $pr_updated_at, Created: $pr_created_at"

              # Debug: If we have null values, print raw data
              if [[ "$pr_updated_at" == "null" || "$pr_created_at" == "null" ]]; then
                  echo "Error: PR #$pr_number has null fields"
                  echo "Raw PR data: $pr_json"
              fi

              # Compare updatedAt date with the date 14 days ago
              if [[ "$pr_updated_at" < "$fourteen_days_ago" && "$pr_created_at" < "$fourteen_days_ago" ]]; then
                  echo "Closing PR #$pr_number (inactive for over 14 days)"
          
                  # Add a comment before closing
                  gh pr comment $pr_number --body "This pull request has been inactive for over 14 days and is now being closed automatically. Feel free to reopen if needed. 🚀"
          
                  # Close the PR
                  gh pr close $pr_number
              else
                  echo "Keeping PR #$pr_number (Not inactive for over 14 days)"
              fi
          done
