name: Delete Old Scratch Branches
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  delete_old_scratch_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Delete scratch branches older than 7 days
        run: |
          #!/bin/bash
          set -e  # Stop on errors

          # Ensure we're on main branch
          git checkout main
          git pull origin main

          # Get current date in seconds
          current_date=$(date +%s)

          # Debug: Print all branches
          echo "Found branches:"
          git for-each-ref --sort=committerdate --format='%(refname:short) %(committerdate:iso8601)' refs/heads/

          # Get all branches
          branches=$(git for-each-ref --sort=committerdate --format='%(refname:short)' refs/heads/)
          for branch in $branches; do
              if [[ "$branch" == scratch/* ]]; then
                  # Get the last commit date of the branch in seconds
                  last_commit_date=$(git log -1 --format="%ct" "$branch")
                  # Calculate the age of the branch in days
                  age=$(( (current_date - last_commit_date) / 86400 ))

                  # Check if the branch is older than 7 days
                  if [ "$age" -gt 7 ]; then
                      echo "Deleting remote branch: $branch (Age: $age days)"
                      git push origin --delete "$branch"
                  else
                      echo "Keeping: $branch (Age: $age days)"
                  fi
              else
                  echo "Skipping branch: $branch (Not a scratch branch)"
              fi
          done
